name: test-clang-format

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: '.'
        exclude: './CMake'
        extensions: 'hxx,h,cxx'
        clangFormatVersion: 8
        style: file
